// Catálogo error_code → texto pt-BR, portado 1:1 de motoka_app
// (lib/src/core/errors/api_error_messages.dart, 201 códigos em 2026-10-05), mais COUPON_CODE_TAKEN,
// TOO_MANY_REQUESTS, AUTH_TOKEN_EXPIRING e TRACKING_STREAM_UNAVAILABLE, que a API tem e o app ainda
// não (check-error-codes no WN-0 e na revisão dele).
// O `detail` do backend nunca vai para a tela. Para conferir códigos novos da API: yarn check-error-codes.
export const API_ERROR_MESSAGES: Readonly<Record<string, string>> = {
  ACCOUNT_DOCUMENT_LOCKED: "O documento só pode ser alterado na atualização cadastral.",
  ACCOUNT_PHONE_CHANGE_REQUIRES_VERIFICATION: "Para trocar o celular, confirme o novo número por SMS.",
  ACCOUNT_PHONE_ONLY: "Esta conta entra pelo celular e não tem senha nem e-mail.",
  ACCOUNT_RETIRED: "Esta conta foi encerrada porque o celular passou para outra pessoa.",
  ACTIVE_TERM_OF_USE_NOT_FOUND: "Não encontramos o termo de uso vigente.",
  ADDRESS_CREATION_FAILED: "Não foi possível salvar o endereço. Tente novamente.",
  ADDRESS_NOT_FOUND: "Endereço não encontrado.",
  APPLICATION_ERROR: "Ocorreu um erro no servidor. Tente novamente mais tarde.",
  AUTH_ERROR: "Não foi possível validar sua sessão. Entre novamente.",
  AUTH_REFRESH_MISSING: "Sua sessão expirou. Entre novamente.",
  AUTH_REFRESH_REUSED: "Sua sessão foi encerrada por segurança. Entre novamente.",
  AUTH_REFRESH_REVOKED: "Sua sessão foi encerrada. Entre novamente.",
  AUTH_SESSION_EXPIRED: "Sua sessão expirou. Entre novamente.",
  AUTH_TOKEN_EXPIRED: "Sua sessão expirou. Entre novamente.",
  AUTH_TOKEN_EXPIRING: "Sua sessão está sendo renovada. Tente de novo.",
  AUTH_TOKEN_INVALID: "Sua sessão não é mais válida. Entre novamente.",
  AUTHZ_USER_NOT_FOUND: "Não encontramos sua conta. Entre novamente.",
  BAD_REQUEST: "Não foi possível concluir a operação. Verifique os dados e tente novamente.",
  BANK_CARD_NOT_FOUND: "Cartão não encontrado.",
  CONFIRMATION_CODE_ALREADY_USED: "Este código já foi utilizado. Solicite um novo.",
  CONFIRMATION_CODE_EXPIRED: "Este código expirou. Solicite um novo.",
  CONFIRMATION_CODE_INVALID: "Código inválido. Confira e tente novamente.",
  CONFIRMATION_CODE_NOT_FOUND: "Código não encontrado. Solicite um novo.",
  CONFLICT: "Esses dados já estão em uso. Verifique e tente novamente.",
  COUPON_ALREADY_REDEEMED: "Esta conta já utilizou um cupom de isenção.",
  COUPON_CODE_TAKEN: "Já existe um cupom com este código.",
  COUPON_EXHAUSTED: "Este cupom já atingiu o limite de usos.",
  COUPON_EXPIRED: "Este cupom expirou.",
  COUPON_INACTIVE: "Este cupom não está mais disponível.",
  COUPON_NOT_FOUND: "Cupom não encontrado. Confira o código.",
  DELIVERY_ACTION_ID_CONFLICT: "Esta ação já foi usada para outra operação. Atualize a tela.",
  DELIVERY_ADDRESS_INVALID: "Informe rua, número, bairro e cidade do endereço.",
  DELIVERY_ADDRESS_LOCKED: "O endereço não pode mais ser alterado.",
  DELIVERY_ALREADY_FINISHED: "Esta entrega já foi encerrada.",
  DELIVERY_ANOTHER_IN_PROGRESS: "Termine a entrega em andamento antes de começar outra.",
  DELIVERY_CANCELLED: "Este pedido foi cancelado. Veja o que fazer com ele.",
  DELIVERY_CODE_CHECK_UNAVAILABLE: "Não foi possível conferir o código agora. Tente de novo.",
  DELIVERY_CODE_INVALID: "Código incorreto. Confira com o cliente.",
  DELIVERY_CODE_LOCKED: "Muitas tentativas. Peça para a loja confirmar a entrega ou informe um problema.",
  DELIVERY_CODE_REQUIRED: "Digite o código de entrega.",
  DELIVERY_CONFIRM_REASON_REQUIRED: "Informe por que a entrega está sendo confirmada sem código.",
  DELIVERY_CUSTOMER_PHONE_INVALID: "Informe o celular do cliente com DDD.",
  DELIVERY_CUSTOMER_PHONE_REQUIRED: "Informe o celular do cliente.",
  DELIVERY_DRIVER_LOCKED_AFTER_PICKUP: "Não dá para trocar o motoboy depois da retirada.",
  DELIVERY_DRIVER_NOT_IN_TEAM: "Este motoboy não está ativo na sua equipe.",
  DELIVERY_DRIVER_NOT_ON_SHIFT: "Este motoboy não está em turno agora.",
  DELIVERY_INVALID_TRANSITION: "Esta ação não vale para a entrega neste momento.",
  DELIVERY_NOT_FOUND: "Entrega não encontrada.",
  DELIVERY_PAYMENT_INVALID: "Confira os dados do pagamento.",
  DELIVERY_PROBLEM_DESCRIPTION_REQUIRED: "Descreva o problema para a loja.",
  DELIVERY_REINFORCEMENT_INVALID: "Este motoboy não está num serviço avulso ativo da sua loja.",
  DELIVERY_SHIFT_NOT_STARTED: "Comece o turno nesta loja antes de retirar a entrega.",
  DELIVERY_TRACKING_EXPIRED: "Este acompanhamento terminou.",
  DELIVERY_TRACKING_NOT_FOUND: "Link de acompanhamento não encontrado.",
  DELIVERY_TRACKING_UNAVAILABLE: "Esta entrega não tem link de acompanhamento do Motoka.",
  DOCUMENT_ALREADY_REGISTERED: "Este documento já está cadastrado.",
  DOMAIN_ERROR: "Não foi possível concluir a operação. Verifique os dados e tente novamente.",
  DRIVER_KYC_ALREADY_DECIDED: "Este envio de documentos já foi decidido.",
  DRIVER_KYC_ALREADY_PENDING: "Seus documentos já estão em análise. Atualize a tela para ver a situação.",
  DRIVER_KYC_CONSENT_REQUIRED: "É preciso aceitar os termos antes de enviar seus documentos.",
  DRIVER_KYC_DRIVER_NOT_CLEARED: "Este motoboy ainda não teve os documentos aprovados e não pode ser vinculado ao pedido.",
  DRIVER_KYC_FILE_INVALID_TYPE: "Formato de arquivo não aceito. A CNH pode ser PDF ou foto; a selfie, só foto.",
  DRIVER_KYC_FILE_MISSING: "Envie a CNH e a selfie.",
  DRIVER_KYC_FILE_TOO_LARGE: "Um dos arquivos ficou grande demais. Envie um arquivo menor ou tire a foto novamente com menos zoom.",
  DRIVER_KYC_NOT_CLEARED: "Você precisa ter seus documentos aprovados para se candidatar a um serviço. Envie seus documentos no seu perfil.",
  DRIVER_KYC_PAYLOAD_TOO_LARGE: "Os arquivos somam mais que o permitido. Envie arquivos menores.",
  DRIVER_KYC_REJECTION_REASON_REQUIRED: "Informe o motivo da reprovação.",
  DRIVER_KYC_RESUBMIT_TOO_SOON: "Aguarde alguns minutos antes de enviar novamente.",
  DRIVER_KYC_SUBMISSION_NOT_FOUND: "Envio de documentos não encontrado.",
  DRIVER_KYC_UPLOAD_FAILED: "Não foi possível enviar seus documentos agora. Tente novamente em instantes.",
  DRIVER_NOT_FOUND: "Motoboy não encontrado.",
  EMAIL_ALREADY_REGISTERED: "Este e-mail já está cadastrado.",
  EMAIL_IN_USE: "Este e-mail já está em uso por outra conta.",
  EMAIL_NOT_CONFIRMED: "Confirme seu e-mail para continuar.",
  EMAIL_NOT_VERIFIED: "Confirme seu e-mail para continuar.",
  ESTABLISHMENT_NOT_FOUND: "Estabelecimento não encontrado.",
  FORBIDDEN: "Você não tem permissão para realizar esta ação.",
  GONE: "Recurso não está mais disponível",
  HTTP_ERROR: "Recurso não disponível.",
  INTERNAL_ERROR: "Ocorreu um erro, tente novamente mais tarde.",
  LOGIN_INVALID_CREDENTIALS: "CPF/CNPJ, e-mail ou senha incorretos.",
  LOGIN_INVALID_PASSWORD: "CPF/CNPJ, e-mail ou senha incorretos.",
  LOGIN_USER_INACTIVE: "Sua conta está inativa. Fale com o suporte.",
  LOGIN_USER_NOT_FOUND: "CPF/CNPJ, e-mail ou senha incorretos.",
  NEGOTIATION_ACCEPT_WRONG_PARTY: "A última oferta precisa ser aceita pela outra parte.",
  NEGOTIATION_ALREADY_LINKED: "Você já está vinculado a este pedido.",
  NEGOTIATION_CANCEL_WRONG_PARTY: "Apenas quem iniciou a negociação pode cancelá-la.",
  NEGOTIATION_CANNOT_OFFER: "Não é possível enviar uma nova oferta agora.",
  NEGOTIATION_ESTABLISHMENT_CANNOT_START: "Apenas o motoboy pode iniciar uma negociação.",
  NEGOTIATION_FINALIZED_CANNOT_ACCEPT: "Esta negociação já foi finalizada e não pode ser aceita.",
  NEGOTIATION_FINALIZED_CANNOT_CANCEL: "Esta negociação já foi finalizada e não pode ser cancelada.",
  NEGOTIATION_FINALIZED_CANNOT_REJECT: "Esta negociação já foi finalizada e não pode ser recusada.",
  NEGOTIATION_IN_PROGRESS: "Já existe uma negociação em andamento para este pedido.",
  NEGOTIATION_NO_OFFERS: "Esta negociação ainda não tem nenhuma oferta.",
  NEGOTIATION_NOT_FOUND: "Negociação não encontrada.",
  NEGOTIATION_OFFER_NOT_PENDING: "A última oferta desta negociação não está mais em aberto.",
  NEGOTIATION_REJECT_WRONG_PARTY: "A última oferta precisa ser recusada pela outra parte.",
  NOT_FOUND: "Não encontramos o que você procura.",
  NOTIFICATION_NOT_FOUND: "Notificação não encontrada.",
  ORDER_ALREADY_CANCELLED: "Este pedido já foi cancelado.",
  ORDER_CANNOT_BE_PAID: "Este pedido não pode ser pago no momento.",
  ORDER_CANNOT_FINISH: "Este serviço não pode ser finalizado no momento.",
  ORDER_CANNOT_START: "Este serviço não pode ser iniciado no momento.",
  ORDER_CARD_NOT_FOUND: "Cartão não encontrado. Selecione outro cartão.",
  ORDER_DRIVER_ALREADY_SUBSCRIBED: "Você já está cadastrado neste pedido.",
  ORDER_DRIVER_NOT_ASSIGNED: "Este motoboy não está vinculado ao pedido.",
  ORDER_END_DATE_INVALID: "A data de término deve ser posterior à data de início.",
  ORDER_ESTABLISHMENT_CANNOT_SUBSCRIBE: "Estabelecimentos não podem se candidatar a pedidos.",
  ORDER_FINALIZED_CANNOT_CANCEL: "Pedidos finalizados não podem ser cancelados.",
  ORDER_NOT_AVAILABLE: "Este pedido não está mais disponível.",
  ORDER_NOT_AVAILABLE_FOR_NEGOTIATION: "Este pedido não está mais aberto para negociação.",
  ORDER_NOT_FOUND: "Pedido não encontrado.",
  ORDER_PAYMENT_CREATION_FAILED: "Não foi possível iniciar o pagamento. Tente novamente.",
  ORDER_PAYMENT_NOT_FOUND: "Nenhuma cobrança foi encontrada para este pedido.",
  ORDER_POSITIONS_FULL: "As vagas deste pedido já foram preenchidas.",
  ORDER_PRICE_PER_DELIVERY_REQUIRED: "Informe o valor por entrega.",
  ORDER_START_DATE_EXPIRED: "O horário de início deste serviço já passou. Crie um novo serviço com outra data.",
  ORDER_START_DATE_INVALID: "A data de início deve ser posterior à data atual.",
  ORDER_USER_NOT_ESTABLISHMENT: "Apenas estabelecimentos podem criar pedidos.",
  ORDER_VALUE_AND_PRICE_PER_DELIVERY_REQUIRED: "Informe o valor do pedido e o valor por entrega.",
  ORDER_VALUE_NOT_POSITIVE: "O valor informado deve ser maior que zero.",
  ORDER_VALUE_REQUIRED: "Informe o valor do pedido.",
  PAYMENT_GATEWAY_ERROR: "Não foi possível falar com o serviço de pagamento. Tente novamente.",
  PAYMENT_INVALID_FEE_TYPE: "Não foi possível calcular a taxa deste pagamento.",
  PAYMENT_METHOD_UNSUPPORTED: "Forma de pagamento não disponível.",
  PAYMENT_NO_PROCESSOR: "Forma de pagamento indisponível no momento.",
  PAYMENT_NOT_FOUND: "Pagamento não encontrado.",
  PAYMENT_NOT_REFUNDABLE: "Este pagamento não pode ser estornado.",
  PHONE_ACCOUNT_NOT_FOUND: "Não encontramos conta com este celular. Peça o convite para a loja.",
  PHONE_ALREADY_REGISTERED: "Este celular já está numa conta do Motoka. Se a conta é sua, entre com e-mail e senha. Se não é, toque em \"Essa conta não é minha\".",
  PHONE_ALREADY_VERIFIED_ELSEWHERE: "Este celular já está confirmado em outra conta.",
  PHONE_AUTH_PHONE_NOT_SUPPORTED: "Use um celular do Brasil com DDD.",
  PHONE_AUTH_TOKEN_INVALID: "Não foi possível confirmar seu número. Tente de novo.",
  PHONE_AUTH_TOKEN_STALE: "A confirmação do número expirou. Peça um novo código.",
  PHONE_AUTH_UNAVAILABLE: "Entrada por celular indisponível no momento.",
  PHONE_LOGIN_REINVITE_REQUIRED: "Faz tempo que você não entra. Peça um novo convite para a loja.",
  PHONE_VERIFY_NOT_ALLOWED: "Confirmação por celular não disponível para esta conta.",
  PROFILE_PHOTO_URL_FAILED: "Não foi possível enviar a foto. Tente novamente.",
  RATE_LIMIT_EXCEEDED: "Muitas requisições. Aguarde um pouco e tente de novo.",
  REFUND_GATEWAY_ERROR: "Não foi possível processar o estorno. Tente novamente.",
  REFUND_NOT_SUPPORTED: "O estorno não está disponível para esta forma de pagamento.",
  ROLE_ALREADY_EXISTS: "Já existe um perfil de acesso com esse nome.",
  ROLE_INVALID_PERMISSIONS: "As permissões informadas são inválidas.",
  ROLE_NOT_FOUND: "Perfil de acesso não encontrado.",
  ROUTE_NOT_FOUND: "Recurso não disponível.",
  SESSION_USER_INACTIVE: "Sua conta está inativa. Fale com o suporte.",
  SESSION_USER_NOT_FOUND: "Não encontramos sua conta. Entre novamente.",
  SYSTEM_ROLE_CANNOT_DELETE: "Este perfil de acesso não pode ser excluído.",
  SYSTEM_ROLE_CANNOT_RENAME: "Este perfil de acesso não pode ser renomeado.",
  TEAM_ALREADY_MEMBER: "Você já faz parte desta equipe.",
  TEAM_DEAL_INVALID: "Combinado inválido para o tipo de remuneração.",
  TEAM_INVITE_ALREADY_USED: "Este convite já foi usado.",
  TEAM_INVITE_EXPIRED: "Este convite expirou. Peça um novo para a loja.",
  TEAM_INVITE_LINK_LIMIT_REACHED: "Este link atingiu o limite de entradas de hoje. Peça um convite à loja.",
  TEAM_INVITE_NOT_DECLINABLE: "Este convite não pode ser recusado.",
  TEAM_INVITE_NOT_FOUND: "Convite não encontrado.",
  TEAM_INVITE_PHONE_MISMATCH: "Este convite foi enviado para outro número.",
  TEAM_INVITE_RATE_LIMITED: "Muitos convites hoje. Tente de novo amanhã.",
  TEAM_INVITE_RESEND_TOO_SOON: "Aguarde um minuto para reenviar o convite.",
  TEAM_INVITE_REVOKED: "Este convite foi cancelado pela loja.",
  TEAM_INVITEE_ALREADY_MEMBER: "Esse motoboy já está na sua equipe.",
  TEAM_MEMBER_ALREADY_ENDED: "Este vínculo já foi encerrado.",
  TEAM_MEMBER_NOT_ACTIVE: "Este motoboy não está ativo na equipe.",
  TEAM_MEMBER_NOT_FOUND: "Motoboy não encontrado na equipe.",
  TEAM_MEMBER_NOT_PAUSED: "Este motoboy não está pausado.",
  TEAM_REJOIN_REQUIRES_INVITE: "A loja tirou você da equipe. Para voltar, peça um novo convite à loja.",
  TEAM_PIX_KEY_INVALID: "Chave Pix inválida. Confira o tipo e o valor.",
  TEAM_SETTLEMENT_ADJUSTMENT_INVALID: "Ajuste inválido. Confira o valor e escreva o motivo.",
  TEAM_SETTLEMENT_ALREADY_CLOSED: "Este acerto já foi confirmado e não muda mais.",
  TEAM_SETTLEMENT_AWAITING_DRIVER: "O motoboy ainda não conferiu o acerto. Se ele não responder em 24 h, o acerto libera para você.",
  TEAM_SETTLEMENT_DEAL_INCOMPLETE: "Informe o valor combinado com o motoboy antes de confirmar.",
  TEAM_SETTLEMENT_DISPUTE_REASON_REQUIRED: "Conte o que está errado no acerto.",
  TEAM_SETTLEMENT_HAS_PENDING_LINES: "Ainda há entregas deste turno sem desfecho. Resolva-as antes de confirmar.",
  TEAM_SETTLEMENT_INVALID_STATE: "Esta ação não vale para o acerto neste momento.",
  TEAM_SETTLEMENT_LINE_NOT_EXCLUDABLE: "Esta entrega não pode ser retirada do acerto.",
  TEAM_SETTLEMENT_NOT_CONFIRMED: "Confirme o acerto antes de marcar como pago.",
  TEAM_SETTLEMENT_NOT_FOUND: "Acerto não encontrado.",
  TEAM_SETTLEMENT_RAIN_NOT_IN_DEAL: "O combinado deste turno não tem adicional de chuva.",
  TEAM_SETTLEMENT_VERSION_CONFLICT: "O acerto mudou enquanto você conferia. Confira os valores de novo.",
  TEAM_SESSION_ALREADY_ENDED: "Este turno já foi encerrado.",
  TEAM_SESSION_ALREADY_OPEN: "Você já está em outro turno. Encerre antes de começar este.",
  TEAM_SESSION_HAS_ACTIVE_DELIVERIES: "Termine ou devolva as entregas antes de encerrar o turno.",
  TEAM_SESSION_NOT_FOUND: "Turno em andamento não encontrado.",
  TEAM_SHIFT_ALREADY_STARTED: "Este turno já foi iniciado.",
  TEAM_SHIFT_DRIVER_BUSY: "Esse motoboy já tem turno nesse horário.",
  TEAM_SHIFT_ENDED: "Este turno já foi encerrado.",
  TEAM_SHIFT_IN_PAST: "Não dá para criar turno que já começou.",
  TEAM_SHIFT_IN_PROGRESS: "Este turno está em andamento.",
  TEAM_SHIFT_INVALID_TIME: "Horário do turno inválido.",
  TEAM_SHIFT_NOT_FOUND: "Turno não encontrado.",
  TEAM_SHIFT_NOT_STARTABLE: "Ainda não está na hora de começar este turno.",
  TEAM_WEEK_START_INVALID: "A semana precisa começar numa segunda-feira.",
  TERM_OF_USE_NOT_FOUND: "Termo de uso não encontrado.",
  TERM_OF_USE_URL_FAILED: "Não foi possível abrir o termo de uso. Tente novamente.",
  TOO_MANY_REQUESTS: "Muitas tentativas em pouco tempo. Aguarde alguns instantes e tente novamente.",
  TRACKING_BATCH_INVALID: "Não foi possível enviar sua localização. Tente de novo.",
  TRACKING_CONSENT_REQUIRED: "Aceite o uso da localização para começar o turno.",
  TRACKING_CONSENT_VERSION_INVALID: "Os termos de localização mudaram. Leia e aceite de novo.",
  TRACKING_NOT_ON_SHIFT: "Você não está em turno. Comece o turno para enviar a localização.",
  TRACKING_SESSION_NOT_FOUND: "Turno não encontrado.",
  TRACKING_STREAM_UNAVAILABLE: "O mapa ao vivo está sem atualização em tempo real. Atualizando de tempos em tempos.",
  UNKNOWN_ERROR: "Ocorreu um erro, tente novamente mais tarde.",
  USER_ALREADY_BLOCKED: "Esta conta já está bloqueada.",
  USER_CREATION_FAILED: "Não foi possível criar sua conta. Tente novamente.",
  USER_DOCUMENT_INVALID: "O documento informado não é válido.",
  USER_ESTABLISHMENT_DOCUMENT_INVALID: "Informe um CNPJ válido para conta de estabelecimento.",
  USER_NOT_BLOCKED: "Esta conta não está bloqueada.",
  USER_NOT_FOUND: "Usuário não encontrado.",
  USER_NOT_FOUND_OR_INACTIVE: "Usuário não encontrado ou inativo.",
  USER_PASSWORD_CONFIRMATION_MISMATCH: "A confirmação não corresponde à nova senha.",
  USER_PASSWORD_INCORRECT: "A senha atual está incorreta.",
  USER_PASSWORD_WEAK: "A senha não atende aos requisitos de segurança.",
  DELIVERY_DRIVER_SHIFT_NOT_STARTED: "Este motoboy ainda não começou o turno.",
  DELIVERY_DRIVER_SHIFT_ENDED: "Este motoboy já encerrou o turno.",
  INTEGRATION_AUTH_EXPIRED: "O código expirou. Gere um novo código.",
  INTEGRATION_AUTH_FAILED: "Não foi possível falar com o parceiro agora. Tente de novo em instantes.",
  INTEGRATION_AUTH_STATE_INVALID: "Não foi possível confirmar a conexão. Comece de novo pelo painel.",
  INTEGRATION_EXTERNAL_DRIVER_NOT_FOUND: "Entregador não encontrado ou inativo no parceiro.",
  INTEGRATION_EXTERNAL_DRIVER_TAKEN: "Esse entregador já está vinculado a outro motoboy.",
  INTEGRATION_RATE_LIMITED: "Muitas ações seguidas. Tente em instantes.",
  INTEGRATION_REAUTH_REQUIRED: "A conexão com o parceiro caiu. Reconecte a integração.",
  DELIVERY_ACCEPT_DEADLINE_PASSED: "O prazo acabou e o pedido foi recusado.",
  DELIVERY_ACCEPT_NO_DRIVER: "Nenhum motoboy em turno pode levar este pedido agora.",
  DELIVERY_NOT_AWAITING_ACCEPTANCE: "Este pedido não está mais aguardando aceite.",
  INTEGRATION_MERCHANT_ID_INVALID: "O ID da loja no Open Delivery tem pelo menos 36 caracteres. Copie de novo do seu sistema.",
  INTEGRATIONS_NOT_CONFIGURED: "As integrações ainda não estão disponíveis. Tente de novo mais tarde.",
  INTEGRATION_CREDENTIAL_RATE_LIMITED: "Você gerou muitas credenciais na última hora. Tente de novo mais tarde.",
  INTEGRATION_MERCHANT_ID_TAKEN: "Este ID de loja já está ligado a outra conta do Motoka.",
  INTEGRATION_NOT_FOUND: "Integração não encontrada. Salve os dados da integração primeiro.",
  INTEGRATION_TYPE_UNAVAILABLE: "Esta integração ainda não está disponível.",
  INTEGRATION_WEBHOOK_URL_INVALID: "Use um endereço https público, na porta 443 ou 8443, sem usuário e senha.",
  TEAM_REMINDER_NOT_APPLICABLE: "Este motoboy não está em turno agora ou já está com a localização ligada.",
  TEAM_REMINDER_TOO_SOON: "O lembrete acabou de ser enviado. Aguarde alguns minutos para reenviar.",
  TEAM_SESSION_END_TOO_EARLY: "O turno ainda não chegou ao horário de terminar.",
  USER_PHONE_NUMBER_INVALID: "O telefone informado não é válido.",
  VALIDATION_ERROR: "Confira os dados preenchidos e tente novamente.",
  WEB_AUTH_ACCOUNT_NOT_ALLOWED: "O painel é só para estabelecimentos.",
  WEB_AUTH_ORIGIN_NOT_ALLOWED: "Requisição não permitida.",
  WEBHOOK_SIGNATURE_INVALID: "Não foi possível confirmar o pagamento. Tente novamente.",
  WEBHOOK_SIGNATURE_MISSING: "Não foi possível confirmar o pagamento. Tente novamente.",
};
